test:
  image: "golang:1.15.4-buster"
  stage: test
  script:
    - go test ./...
deploy:
  stage: deploy
  image: "docker:19.03.12"
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.12-dind
  script:
    - docker build . -t $DOCKER_IMAGE_TAG:$CI_JOB_ID$CI_COMMIT_SHORT_SHA
    - docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $DOCKER_IMAGE_TAG:$CI_JOB_ID$CI_COMMIT_SHORT_SHA
  only:
    - master
