test:
  image: "golang:1.15.4-buster"
  stage: test
  script:
    - go test ./...
deploy:
  stage: deploy
  image: "docker:19.03.12"
  before_script:
    - apk add curl
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME_VK: "$DOCKER_IMAGE_TAG_VK:$CI_JOB_ID.$CI_COMMIT_SHORT_SHA"
    IMAGE_NAME_TG: "$DOCKER_IMAGE_TAG_TG:$CI_JOB_ID.$CI_COMMIT_SHORT_SHA"
  services:
    - docker:19.03.12-dind
  script:
    - docker build . -t $DOCKER_IMAGE_TAG_VK -t $IMAGE_NAME_VK --build-arg VERSION=vk
    - docker build . -t $DOCKER_IMAGE_TAG_TG -t $IMAGE_NAME_TG --build-arg VERSION=telegram
    - docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $IMAGE_NAME_VK
    - docker push $DOCKER_IMAGE_TAG_VK
    - docker push $IMAGE_NAME_TG
    - docker push $DOCKER_IMAGE_TAG_TG
    - "curl -X POST -H \"Authorization: Bearer $GOCD_ACCESS_TOKEN\" -d '{\"repository_url\": \"https://gitlab.com/flygrounder/go-mtg-vk\"}' -H \"Accept: application/vnd.go.cd.v2+json\" -H \"Content-Type: application/json\" https://gocd.flygrounder.ru/go/api/admin/materials/git/notify"
  only:
    - master
