version: "3.3"
services:
  vk:
    image: flygrounder/go-mtg-vk:latest
    environment:
      - VK_TOKEN
      - VK_SECRET_KEY
      - VK_GROUP_ID
      - VK_CONFIRMATION_STRING

    ports:
      - "127.0.0.1:8888:8000"
    restart: "always"
  telegram:
      image: flygrounder/go-mtg-telegram:latest
      environment:
        - TG_TOKEN
      restart: "always"
  redis:
    image: "redis:6.0.9"
    restart: "always"
