version: "3.3"
services:
  web:
    image: flygrounder/go-mtg-vk:latest
    environment:
      - VK_TOKEN
      - VK_SECRET_KEY
      - VK_GROUP_ID
      - VK_CONFIRMATION_STRING

    ports:
      - "127.0.0.1:8888:80"
    restart: "always"
  redis:
    image: "redis:6.0.9"
    restart: "always"
